---
title: "ARMAX"
output:
  html_notebook: default
  html_document:
    df_print: paged
  pdf_document: default
---

# ARMAX model (1,0,2)####

vi bruger først vores arma 1,0,2 model til armax
```{r}

testxreg <-as.data.frame(cbind(xregcon/1000,xreghydro,xregtemp)[1:2191,] )
for (i in 1:dim(testxreg)[1]) {
  for (j in 1:dim(testxreg)[2]) {
    if(is.na(testxreg[i,j])==TRUE){
      testxreg[i,j] <- 0
    }
   
  }
}
armax1_0_2 <- TSA::arima(X_t,order=c(1,0,2), seasonal = list(order = c(0, 0, 0)),xreg = testxreg, include.mean = F)
rmse(X_t,fitted.values(armax1_0_2))
plot(as.data.frame(fitted.values(armax1_0_2)),col="red");lines(X_t,col="blue")
```

vi tjekker det mod en arma(1,0,2) uden xreg

```{r}



arma1_2 <- TSA::arima(X_t,order=c(1,0,2), seasonal = list(order = c(0, 0, 0)), include.mean = F)

di_ACF <- acf(armax1_0_2$residuals ,plot = FALSE)
di_acf <- with(di_ACF, data.frame(lag, acf))
ggplot(data = di_acf, mapping = aes(x = lag, y = acf)) +
  geom_hline(aes(yintercept = 0)) +
  geom_segment(mapping = aes(xend = lag, yend = 0))+ggtitle("ARMAX (1,0,2)")+
  ylab("ACF")+geom_hline(aes(yintercept=0.042),col="blue",linetype=2)+
  geom_hline(aes(yintercept=-0.042),col="blue",linetype=2)

rmse(X_t,fitted.values(arma1_2))
plot(as.data.frame(fitted.values(arma1_2)),col="red");lines(X_t,col="blue")
```

# ARMAX model (3,0.19,4)####

```{r}

testxreg <-as.data.frame(cbind(xregcon,xreghydro,xregtemp)[31:2221,] )
testxreg <-as.data.frame(ar3[3:2193,])
for (i in 1:dim(testxreg)[1]) {
  for (j in 1:dim(testxreg)[2]) {
    if(is.na(testxreg[i,j])==TRUE){
      testxreg[i,j] <- 0
    }
    
  }
}
armax3_019_4 <- TSA::arima(frakdiff(X_t,0.19),order=c(3,0,4), seasonal = list(order = c(0, 0, 0)),xreg <- testxreg, include.mean = F)
sarmax3_019_4 <- arfima::arfima(X_t,order=c(3,0,4),fixed=list(frac=0.19),xreg = testxreg,dmean = F,itmean = F)

  
rmse(frakdiff(X_t,0.19),as.data.frame(fitted.values(sarmax3_019_4))[,1])


  
di_ACF <- acf(armax3_019_4$residuals ,plot = FALSE)
di_acf <- with(di_ACF, data.frame(lag, acf))
ggplot(data = di_acf, mapping = aes(x = lag, y = acf)) +
  geom_hline(aes(yintercept = 0)) +
  geom_segment(mapping = aes(xend = lag, yend = 0))+ggtitle("ARMAX (3,0.19,4)")+
  ylab("ACF")+geom_hline(aes(yintercept=0.042),col="blue",linetype=2)+
  geom_hline(aes(yintercept=-0.042),col="blue",linetype=2)
```

# consumption as only xreg  #######
```{r}

conxreg <-as.data.frame(cbind(xregcon)[1:2191,] )
for (i in 1:dim(conxreg)[1]) {
  for (j in 1:dim(conxreg)[2]) {
    if(is.na(conxreg[i,j])==TRUE){
      conxreg[i,j] <- 0
    }
    
  }
}
con_armax3_019_4 <- TSA::arima(frakdiff(X_t,0.19),order=c(3,0,4), seasonal = list(order = c(0, 0, 0)),xreg <- conxreg, include.mean = F)

conrmse <- rmse(frakdiff(X_t,0.19),as.data.frame(fitted.values(con_armax3_019_4))[,1])
```

# temp as only xreg ######### 
```{r}
tempxreg <-as.data.frame(cbind(xregtemp)[1:2191,] )
for (i in 1:dim(tempxreg)[1]) {
  for (j in 1:dim(tempxreg)[2]) {
    if(is.na(tempxreg[i,j])==TRUE){
      tempxreg[i,j] <- 0
    }
    
  }
}
temp_armax3_019_4 <- TSA::arima(frakdiff(X_t,0.19),order=c(3,0,4), seasonal = list(order = c(0, 0, 0)),xreg <- tempxreg, include.mean = F)

temprmse <- rmse(frakdiff(X_t,0.19),as.data.frame(fitted.values(temp_armax3_019_4))[,1])

rmse(frakdiff(X_t,0.19),as.data.frame(fitted.values(temp_armax3_019_4))[,1])
```



vi prøver med auto arima og xreg
```{r}
aarmax <- auto.arima(X_t,xreg = as.matrix(testxreg))
rmse(X_t,aarmax$fitted)
plot(aarmax$fitted,col="red",type="l");lines(X_t,col="blue")
acf(aarmax$residuals)
qqnorm(aarmax$residuals)
qqline(aarmax$residuals)


```

 

